"""
Unit & Contract Tests for Interactive Symptom & Pain Location Mapping.
Verifies data structures, patient-reported location formatting, non-inference of organs,
conflict handling, and ClinicalMemory slot compatibility.
"""

import pytest
from contracts.dialogue import ClinicalSlot, DialogueState


class TestBodyMapContracts:
    """Test suite for Body Map data model and clinical safety rules."""

    def test_patient_reported_location_format(self):
        """Test formatting of patient-reported location without organ inference."""
        region = "abdomen"
        side = "right"
        depth = "internal"

        # Format location string as generated by BodyMapSelector
        side_text = side.capitalize()
        depth_text = "Internal / Deep" if depth == "internal" else "External / Skin level"
        location_text = f"{side_text} Abdomen / Stomach Area ({depth_text}, patient-reported)"

        assert "Right" in location_text
        assert "Abdomen" in location_text
        assert "Internal" in location_text
        # Critical Safety Rule: MUST NOT infer organ names
        assert "liver" not in location_text.lower()
        assert "kidney" not in location_text.lower()
        assert "stomach_organ" not in location_text.lower()

    def test_multiple_area_selection(self):
        """Test multiple body map area selections are preserved independently."""
        loc1 = {
            "id": "abdomen_right_internal_1",
            "regionId": "abdomen",
            "side": "right",
            "depth": "internal",
            "formattedSummary": "Right Abdomen / Stomach Area — Internal / Deep",
        }
        loc2 = {
            "id": "lower_back_center_external_2",
            "regionId": "lower_back",
            "side": "center",
            "depth": "external",
            "formattedSummary": "Center Lower Back / Flank — External / Skin level",
        }

        selections = [loc1, loc2]
        combined_string = "; ".join(l["formattedSummary"] for l in selections)

        assert len(selections) == 2
        assert "Right Abdomen" in combined_string
        assert "Lower Back" in combined_string
        assert ";" in combined_string

    def test_conflict_handling_preserves_both_sources(self):
        """Test that voice extraction and body map selection do not silently overwrite each other."""
        voice_reported_location = "Left side chest"
        body_map_location = "Right Abdomen / Stomach Area — Internal / Deep"

        dialogue_state = DialogueState(
            collected_info={
                ClinicalSlot.LOCATION: body_map_location,
            },
            missing_slots=[],
        )

        # Both sources must remain traceable in state
        assert dialogue_state.collected_info[ClinicalSlot.LOCATION] == body_map_location
        assert voice_reported_location != body_map_location

    def test_clinical_slot_location_compatibility(self):
        """Test that ClinicalSlot.LOCATION receives body map data without breaking schema."""
        state = DialogueState(
            collected_info={},
            missing_slots=[ClinicalSlot.LOCATION],
        )

        body_map_summary = "Right Abdomen / Stomach Area — Internal / Deep"
        state.collected_info[ClinicalSlot.LOCATION] = body_map_summary
        if ClinicalSlot.LOCATION in state.missing_slots:
            state.missing_slots.remove(ClinicalSlot.LOCATION)

        assert state.collected_info[ClinicalSlot.LOCATION] == body_map_summary
        assert ClinicalSlot.LOCATION not in state.missing_slots
