"""
Physician accept/edit/reject workflow (PRD §13.3): "Accept, edit or reject
— always — Nothing enters the record unsigned. Status remains preliminary
until the physician signs, then becomes final."
"""

from typing import List, Optional

from ayusetu.ai.clinical.summary.contracts import (
    ClinicalSummary,
    RejectionReason,
    SummaryEdit,
    SummaryRejection,
    SummaryStatus,
)


class AlreadySignedError(Exception):
    pass


def sign(summary: ClinicalSummary, physician_id: str) -> ClinicalSummary:
    """Transitions preliminary -> final. Nothing before this call is final."""
    if summary.status == SummaryStatus.FINAL:
        raise AlreadySignedError(f"Summary for encounter {summary.encounter_id} is already final.")
    summary.status = SummaryStatus.FINAL
    summary.signed_by = physician_id
    from datetime import datetime, timezone

    summary.signed_at = datetime.now(timezone.utc)
    return summary


def edit_field(summary: ClinicalSummary, slot_path: str, new_value: Optional[str], reason: str, editor: str) -> SummaryEdit:
    """
    Applies a physician edit to a structured_history field (or
    chief_complaint) and returns the diff record — this IS the training
    signal described in PRD §14.2, aggregated weekly into the "twenty
    fields the system most often gets wrong".
    """
    if summary.status == SummaryStatus.FINAL:
        raise AlreadySignedError(f"Cannot edit a final summary for encounter {summary.encounter_id}.")

    if slot_path == "chief_complaint":
        old_value = summary.chief_complaint
        summary.chief_complaint = new_value
    elif slot_path in summary.structured_history:
        field = summary.structured_history[slot_path]
        old_value = field.value
        field.value = new_value
        field.elicited = new_value is not None
    else:
        raise KeyError(f"Unknown editable field: {slot_path!r}")

    return SummaryEdit(
        slot_path=slot_path,
        old_value=old_value,
        new_value=new_value,
        reason=reason,
        edited_by=editor,
    )


def reject(summary: ClinicalSummary, reason: RejectionReason, rejected_by: str, detail: Optional[str] = None) -> SummaryRejection:
    """
    Records a structured rejection (PRD §13.3 taxonomy: wrong, incomplete,
    irrelevant, unsafe). Does not mutate summary.status — a rejected
    preliminary summary is discarded/regenerated by the caller, not
    silently marked final.
    """
    if summary.status == SummaryStatus.FINAL:
        raise AlreadySignedError(f"Cannot reject a final summary for encounter {summary.encounter_id}.")
    return SummaryRejection(reason=reason, detail=detail, rejected_by=rejected_by)


_PATIENT_TEMPLATES = {
    "en": "You told us about {chief_complaint}. Duration: {duration}. Severity: {severity}.",
    "hi": "आपने {chief_complaint} के बारे में बताया। अवधि: {duration}. गंभीरता: {severity}.",
}


def generate_patient_facing_version(summary: ClinicalSummary, language: str = "en") -> str:
    """
    Plain-language readback in the patient's own language, confirmed by the
    patient during intake (PRD §13.3). Built only from already-generated,
    gate-passed summary fields — never from raw transcript — so it carries
    the same anti-hallucination guarantees as the physician-facing summary.
    """
    template = _PATIENT_TEMPLATES.get(language, _PATIENT_TEMPLATES["en"])
    duration_field = summary.structured_history.get("duration")
    return template.format(
        chief_complaint=summary.chief_complaint or "your symptoms",
        duration=_clause_or_default(summary, "duration", duration_field),
        severity=_clause_or_default(summary, "severity", None),
    )


def _clause_or_default(summary: ClinicalSummary, source_slot: str, field) -> str:
    if field is not None and field.elicited and field.value:
        return field.value
    for clause in summary.hpi_narrative:
        if source_slot in clause.source_slots:
            return clause.text
    return "not specified"
